insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,356,455','BERNARDA','','TORRES','SILVA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,630,527','ELVIA','MARIA','MEDINA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,176,011','ALIRIO','','JURADO','TARAZONA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,158,798','JAIRO','','GUERRERO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('13,750,049','AURELIANO','','QUIROGA','SANABRIA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('108,828','SAUL','','PRECIADO','CHAPARRO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,362,432','CRISANTO','','MONGUI','CHAVARRO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,004,343','CLOTILDE','','GONZALEZ','GONZALEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,006,657','ANA','DE JESUS','LEAL','DE HERRERA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,817,189','FRANCISCO','JAVIER','MORENO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,398,143','JOSE','ANTONIO','MENDEZ','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,259,010','GORGONIO','','FAJARDO','REAL');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,755,682','MARIA','DE LOS ANGELES','ALMARIO','FAJARDO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('175,922','ISAIAS','','AVILA','MENDEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,294,776','LIBARDO','','MORA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,279,895','HECTOR','DE JESUS','GUZMAN','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,799,181','JOSE','ESTEBAN','CAMACHO','MARIN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('91,011,822','SEGUNDO','RAFAEL','FORERO','HURTADO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,335','MARIA','ALIS','VERGARA','GOMEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,282,259','HERNAN','','PUENTES','SANCHEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,279,854','SAMUEL','','TELLEZ','DIAZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,559','MARIA','NORBY','AVALO','DE CARDONA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,381','JOSE','CUSTODIO','GUTIERREZ','SANCHEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,125','ROSALINA','','VEGA','GARZON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,430','JOSE','BENJAMIN','VALERO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('489,585','PEDRO','LUIS','LOPEZ','CARDONA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('497,202','JOSE','ALBERTO','ROJAS','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,793,125','CRISPIN','','PEREZ','CARVAJAL');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,904,876','MARIA','TERESA DE JESUS','AVENDANO','SANCHEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('486,696','VICENTE','ANIBAL','GUZMAN','CIFUENTES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,636,489','PEDRO','PABLO','NARVAEZ','TOSE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,340,326','HECTOR','DEJESUS','RESTREPO','ALVAREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,293,154','NEFTALI','','HERRERA','CORREA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,685,251','BENJAMIN','','GRISALES','CORREA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,636,249','DANIEL','','ESCOBAR','BALANTA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,318','MARIA','ENERIED','VARGAS','ISAZA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('371,472','PEDRO','PABLO','ROMERO','CASTIBLANCO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,641,827','ARNULFO','','HERRERA','ARANGO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('321,875','JORGE','ABEL','RODRIGUEZ','ARANDA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,200,085','ANA','ROSARIO','SUAREZ','DE SANTIAGO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,943,565','BLANCA','MARIA','BALLEN','GARCIA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,024,576','EUSEBIA','','RIVERA','BUSTOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,132,101','JUDITH','','RODRIGUEZ','DE MAECHA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('39,532,211','MARIA','GLADYS','JIMENEZ','VEGA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,175,722','PABLO','ENRRIQUE','HUESO','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('12,110,631','ALIRIO','','ZAMBRANO','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,323,161','ALCIBIADES','','BAQUERO','MAYORGA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('461,297','ARQUIMEDES','','AYALA','FORERO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,305,010','LUCILA','','GOMEZ','CARRILLO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,350,648','SEBASTIAN','','CONDE','RIVERA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,185','BELARMINO','','LOPEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,842,622','ARTURO','','GALINDO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,965','OSCAR','','SANCHEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,115,490','TERESA','','MONTILLA','MERCHA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,711,115','JAIRO','EMIR','PAZ','BANGUERO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,883,549','FLORESMIRO','','BASTIDAS','CONDE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,193,702','ALEJANDRINA','','RODRIGUEZ','DUSSAN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,200,071','YOLANDA','','MONTOYA','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,854,854','ANA','MARIA','CRUZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('8,000,760','FRANCISCO','','GONGORA','PARRA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,251','GRACIELA','','HERRON','DURAN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,525,473','JOSE','OMAR','OSPINA','HENAO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,972,259','FLOR','MARIA','AVILES','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,239','CLELIA','MATILDE','ABRIL','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,316,410','HUGO','','SALAZAR','GARCIA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('298,626','PABLO','EMILIO','COJI','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,197,751','GERARDINA','.','OROZCO','VIRGUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,680','CARMEN','EMILIA','RESTREPO','DE VALENCIA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,400,351','ARCESIO','','GARCIA','GARCIA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,721','LUZ','ARCELIA','PULIDO','PABON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,177','JACINTO','','PEREZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,712,940','SARA','MARIA','BERNAL','DE CANTILLO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,175','LUIS','ALBERTO','HOSPITAL','FLOREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,805,292','BLANCA','MARIA','BUSTOS','RAMOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,004,983','MARIA','CAROLINA','CALLE','GOMEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('27,968,429','CLAUDINA','','PINEDA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,800,114','ANA','CECILIA','MORENO','BUSTOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('38,974,018','ALBA','MERY','GARCIA','DE ORTIZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,808','FLORENTINO','','SAZA','MURILLO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,564,363','MARIA','ELVIA','SANABRIA','GOMEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,550,219','JESUS','HECTOR','SOTO','SERNA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('31,036,563','ROSA','INES','ALEY','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,736','ROSA','ELENA','SAAVEDRA','DE FAJARDO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,176,670','VICTOR','MANUEL','RODRIGUEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,369','LUIS','GONZAGA','CARDONA','HENAO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,108,293','HERNANDO','','MENA','RUBIANO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,424,011','MARY','OFELIA','LABRADA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,663,617','LUIS','','SANABRIA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,234','SEGUNDO','CLEMENTE','PINEDA','PENA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,163','MARIA','FLORENTINA','SIERRA','VELASCO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,360','ROSA','ADELIA','RODRIGUEZ','DE GALLEGO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,664,147','MARCO','ANTONIO','CASTRO','RODRIGUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,279,554','ANTONIO','','BOLIVAR','ROCHA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('250,521','BUENAVENTURA','','AVILA','ARIAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('120,513','HERIBERTO','','GARZON','TORRES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,398,404','JOSE','HUMBERTO','RODRIGUEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,860','FIDELIGNA','','UBAQUE','SANDOVAL');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,620,433','MARIA','ODILIA','MARTINEZ','DE DURAN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,248,719','EUTIMIO','','LATORRE','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,204,652','ROSALIA','','PAEZ','DE PRIETO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,078','BLANCA','MAUD','OSPINA','DE BETANCOUR');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,808,058','EVANIA','','GONZALEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,350','FRANCISCO','ANTONIO','ORTEGA','PINO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,002,391','FELIPE','','JIMENEZ','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,259,421','HELIODORO','','MARIN','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,172','MARIA','AMPARO','MORENO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,467','MARIA','LUDIVIA','BUITRAGO','BARBOSA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('26,611,548','LESVIA','','ACOSTA','CORTES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,199,647','HERMELINDA','','CHACON','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,465','ESTEBAN','','CAPERA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,743,830','JOSE','SANTOS','SILVA','GUZMAN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,399,727','URIEL','DE JESUS','RUEDA','CANO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,917','NOEL','','LEAL','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,066,126','ALVARO','ALBERTO','LINARES','URREA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,352','MARIA','EDILMA','HUESO','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,145,076','ANA','ADELINA','OSORIO','VDA DE BELTRA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,047,306','TITO','','TIQUE','CAPERA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('26,533,274','BERENICE','','MOSQUERA','DE GUTIERREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,564,812','ROSA','MARIA','GARCIA','PALACIO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('19,064,488','LUIS','ARTURO','CHAVARRO','TORRES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,500,722','ROSA','ISABEL','TAMBO','DE RUBIO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('417,798','FRANCISCO','','MAYORGA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,200,001','CLOTILDE','','CHAGUALA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,216','HUMBERTO','','MERCHAN','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,550,221','LISANDRO','TULIO','RESTREPO','RAVE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('35,375,129','MARIA','CRUZ','GONZALEZ','MORENO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,506','LUIS','ALBERTO','COCA','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,726,058','ARGEMIRO','','MESA','CHACUE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,193','ABIGAIL','','BAQUERO','DE TELLEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,288,270','MARCO','ANTONIO','PINZON','MURILLO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('26,738,232','MARIA','VICENTA','RUBIANO','RODRIGUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('344,089','JOSE','DOLORES','PARADA','PARADA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,434,266','TOMAS','','FERNANDEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('26,583,832','FABIOLA','','MEDINA','DE FALLA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,627','GENOVEVA','','LONDONO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('41,491,876','ROSA','ELENA','MARIN','CRUZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,375,469','DILIA','','REYES','DE RIVERA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('86,001,534','JOSE','HERIBERTO','BERNAL','MORENO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,361','ANA','SILVIA','BARRAGAN','ACOSTA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,024,022','UBALDINA','','CARABALLO','VDA DE PENA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,684,520','ROSA','TULIA','GIL','HERNANDEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('31,036,480','LUZ','ELENA','MOYANO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('325,205','MIGUEL','','PLAZAS','CABRERA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,339,802','POMPILIO','','LUCAS','MARTINEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,437','YESID','','MARTINEZ','MEJIA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('484,407','GABRIEL','ANGEL','MORALES','GUTIERREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,197,662','MARIA','DELIA','DUQUE','DE PORRAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('343,478','JOSE','ANTONIO','RUIZ','MONTANO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,517,251','MARIA','DOMINGA','DIAZ','TORRES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,200,005','AURORA','','SANCHEZ','DE LOPEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,982,854','DOMITILLA','','CUADROS','DE CUADROS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,282,182','LUIS','EDUARDO','MARTINEZ','CHACON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,132,394','JULIA','ROSA','REYES','DE PEREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,356,092','ROSALBA','','RESTREPO','RABE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('462,429','NEVARDO','','ANGULO','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('480,877','HERIBERTO','','OTALVARO','OCAMPO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,529,547','JOSE','DE LA CRUZ','GONZALEZ','TORRES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('418,280','AQUILINO','.','PEDROZA','MORENO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,132,192','URBANA','','VEGA','GONZALES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('31,051,041','ANGELINA','','SANCHEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,259','MARIA','ARNOBIA','QUIROZ','IBARRA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,488,692','ABEL','','GUALTERO','PENAGOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('311,299','LUIS','ALFONSO','BERMUDEZ','TUNJANO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,199,436','FELICITA','','ECHEVERRY','DE LUNA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,145,264','VICTORIA','.','FERNANDEZ','VEGA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,149','MARIA','FLORINDA','PEREZ','MENDOZA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('24,482,116','OLGA','','RAMOS','DE ROA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,150','MARIA','ALICIA','VELASQUEZ','CAMPOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,199,060','ANA','ADELINA','ERAVALO','RODRIGUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,826,349','ZOILA','ROSA','HERNANDEZ','PULIDO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,211,531','FRANCISCO','','ANGULO','PALACIO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,081,834','ANTONIO','','TORRES','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,712,751','GABRIELA','','MANJARREZ','DE MORA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,764','JUAN','','CARDENAS','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,513,703','ANA','JULIA','ORTIZ','ESPITIA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,398,493','RICAURTE','','ORTIZ','NOSSA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,279,991','SIGIFREDO','','FLOREZ','ZAPATA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,054,264','BLANCA','EVELIA','SANCHEZ','HOYOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,193,779','MARIA','ANA ISABEL','MARQUEZ','FORERO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,204,958','MARIA','MABEL','CARDONA','RIOS DE RIOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,963,755','AURORA','LUZ','CARO','ARIAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('345,633','SALVADOR','','MUNOZ','LOPEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,145,053','CLAUDINA','','CRUZ','DE MARIN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,432,481','ANAEL','','TUZARMA','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,451,949','SIGIFREDO','','MONTOYA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,688,615','JOSE','MILAGROS','RIOS','HOLGUIN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('32,444,546','MARIA','ROSALBA','CALLES','JARAMILLO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('41,485,011','ESMILDA','','RAMOS','DE RAMIREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,074,404','MANUEL','ANTONIO','MORENO','NOVOA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('25,077,403','MARIA','NULBIA','VILLADA','DE NARANJO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,387,309','ANA','SOFIA','BAQUERO','ACOSTA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,498,732','LUZ','MERY','RODRIGUEZ','DIAZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,520,038','FEDERICO','','RODRIGUEZ','PUENTES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,203,437','DENIS','','RODRIGUEZ','BERNAL');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('462,316','HOMERO','','MAHECHA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,266','LUIS','OVIDIO','RESTREPO','ALVAREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,350,654','JAIRO','','QUITIAN','CASTRO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,115,892','DIOMEDES','','AGUILAR','GALEON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,350,895','SILVANO','','GOMEZ','AGUILLON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,235,850','JOSE','ISRAEL','MOTATO','LARGO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,271,810','MYRIAN','','OCAMPO','CALLE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,463,382','LUIS','EVELIO','MOLINA','MURILLO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('360,713','CARLOS','ALBERTO','HERRERA','RODRIGUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,028,155','CLODOMIRO','','RODRIGUEZ','LETRADO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,131,026','RAQUELINA','.','CRUZ','DE OLAYA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('310,929','MANUEL','ALFONSO','CANTILLO','MORENO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,680','JUAN','BAUTISTA','BAUTISTA','GUTIERREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,386,416','BELISARIO','','LOPEZ','CHACON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,679,232','VICTORIA','','MORENO','DE BARRAGAN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,313,302','HUMBERTO','','HENAO','PALMA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,691','MARIA','FANY','ARBOLEDA','DE PINZON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,269,001','TOBIAS','','TORRES','RAMIREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,290,273','DAGOBERTO','','TRUJILLO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,211,741','NAZARIO','','MARIN','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,972,251','MARIA','EMIRGEN','BARRAGAN','ACOSTA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,337,071','JOSE','VALENTIN','MUNOZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,379,742','MARIA','ESEDELINA','ARANGO','DE GIRALDO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,279,976','HERNANDO','','MORENO','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,079','MARIA','CAMILA','GARCIA','DE LEON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('24,801,714','MARIELA','','GARIBELLO','ORTIZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,312,435','DIONICIO','','ORTEGA','PINO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,867,460','ISAIAS','','CHICO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,199,972','MARIA','OFELIA','FRANCO','DE AVILA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,901,075','RUBIELA','','OLAYA','RICO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('41,673,598','LEONOR','','GONZALEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,785,793','MARIA','DEL CARMEN','MONTILLA','DE GUERRERO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,279,623','LUIS','ERNESTO','RODRIGUEZ','PUENTES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,342,059','JESUS','ORLANDO','RESTREPO','RAVE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,204,834','SOFIA','','PARRA','DE MEDINA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,250','LUIS','ALONSO','PARRA','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,110','NUBIA','ESTELA','VELASQUEZ','ALZATE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,806,263','LISANDRO','','LEAL','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,122,580','JOSE','HECTOR','GONZALEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,397,582','JOSE','DEL CARMEN','ORJUELA','ORTIZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,434,169','ANA','LUCIA','GOMEZ','ESPINOSA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,043,114','HERMIDES','','MURILLO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,200,027','BLANCA','LIGIA','PEREZ','REYES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,075,943','CLARA','ROSA','PALMA','DE PIEDRAHITA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('35,464,847','ELBECIA','','CASTRO','SASTRE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,509,994','ANA','ADELINA','ALEMAN','DE CAMACHO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,212','MARIA','LEIDA','FLOREZ','DE BONILLA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,160,517','MANUEL','','CESPEDES','TOVAR');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('24,583,226','CLAUDINA','','GARCIA','DE MARTINEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,154,892','PEDRO','ANTONIO','DIAZ','TORRES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,848,013','JOSE','AGUSTIN','PINEROS','CARDENAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,138','ERLINA','','FIERRO','CANO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,627','SIGIFREDO','','RODRIGUEZ','BEDOYA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,225','MARCO','TULIO','VILLAMON','GOMEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,120,026,465','AURORA','','PINTO','LARA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,450,476','CELINA','','ARBOLEDA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,391,921','LUIS','ENRIQUE','RUIZ','REYES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,258,580','OTILIA','','QUIROGA','SUAREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,208','PEDRO','','VALERO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,602,545','MAXIMINA','','PEREZ','VEGA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,106,025','MIGUEL','ANTONIO','CASTILLO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,150','BOHANERGES','','GOMEZ','PALACIO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,488,274','TIBERIO','','RUIZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,218,202','CARMEN','TULIA','SERRANO','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,268,176','FLORIDIANO','','TIQUE','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('224,343','JOSE','FIDELIGNO','CORTES','ROMERO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,106,584','SALVADOR','','ORTIZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,091,928','LUIS','MARIA','SOLER','AMORTEGUI');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,259,355','HERNANDO','','RIVERA','MARIN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('24,995,857','BLANCA','LIGIA','GARCIA','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,633,448','GERARDO','','MORENO','ROMERO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,651,575','ANA','TULIA','ARIAS','DE ESCOBAR');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,817,062','JOSE','CHARLEY','FAJARDO','RAMIREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,200,038','ANGELICA','','RODRIGUEZ','BERNAL');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,176','MARIA','EUGENIA','SUAREZ','GAITAN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('327,140','ANGEL','MARIA','ARAGON','SANCHEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,645,622','AMANDA','','RODRIGUEZ','DE TIQUE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('11,372,327','JULIO','CESAR','ORTIZ','VILLALBA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,199,977','GABRIELA','','VELASCO','DE MESA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,017','ALICIA','','ZAMUDIO','DE ORJUELA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,200,070','MARIA','HORTENCIA','ROJAS','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,760','LUZ','MERY','VALENCIA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,535,646','GERMAN','','CARDOZO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,633,299','GILBERTO','','LOPEZ','CARDONA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,128','ANACLETO','','SUAREZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('8,231,126','IGNACIO','','MORENO','OSORIO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('19,131,914','MAXIMINO','','DIAZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,890,474','PAULINA','','USAQUEN','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,290,304','GABRIEL','ANGEL','GUERRERO','LOAIZA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('376,055','CERVELEON','','PEDRAZA','ROMERO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,003,620','MARIA','ADELA','ALVAREZ','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,559,350','BERNARDA','','MANOSALVA','DE BUITRAGO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,870','JOSE','OMAR','OSPINA','BETANCUR');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('38,570,019','MARIA','ROSALBA','SOTO','DE CARDOZO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,278','JOSE','GUSTAVO','RODRIGUEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('52,580,407','MARGARITA','','MEJIA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('355,622','NICEFORO','','ORTIZ','CASTRO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,283,153','ISMAEL','','VARON','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,758','JESUS','VIRGILIO','GIL','CUBILLOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('10,550,711','ROMULO','ANTONIO','PIEDRAHITA','PALMA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('212,509','DEOGRACIAS','','BELTRAN','MAHECHA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('482,480','PEDRO','ROZO','PEDRAZA','GIL');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('311,170','AQUILINO','','MEDELLIN','VELASQUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,199,998','ETELVINA','','MOLANO','HERNANDEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,301,837','YAMIL','ALONSO','VASQUEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('482,368','JAIME','','BAQUERO','MAYORGA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,489,118','HECTOR','ELIAS','SABOGAL','AREVALO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,316,489','JOSE','VICENTE','GARIBELLO','ORTIZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,396,714','JORGE','ENRIQUE','PARRA','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,488,161','ELISEO','','MONTENEGRO','RENDON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,053,746','EDILIA','','CEBALLOS','TORO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,194','GIL','ROBERTO','GONZALEZ','RUIZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,708','MARIA','ERNESTIA','URREA','LOPEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,895,077','ELEUTERIO','','DUARTE','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,112','PEDRO','ANTONIO','MARTINEZ','CHACON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('461,416','JOSE','DOLORES','DIAZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,072,181','JEREMIAS','','PRIETO','OLARTE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,283,111','JOSUE','','MUNOZ','RODRIGUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,448,951','LUIS','OCTAVIO','VELEZ','SOTO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,164','SERGIO','ANTONIO','MONTOYA','PORRAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,902','MARTHA','ISABEL','VILLAMIL','DE SAAVEDRA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,480','BLANCA','MARIA','COCA','GUZMAN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,131,161','MARIA','DEL CARMEN','VARELA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,670,708','JOSE','RAUL','ALVAREZ','CALLE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,147,034','MARIA','NUBIA','GIRALDO','DE CARDENAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,468','GLADYS','','SUAREZ','MEDELLIN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,200','LUIS','ANGEL','BEDOYA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('19,225,187','JHONY','ANTONIO','PATINO','CARRENO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,810,310','MARIA','DEL CARMEN','ROJAS','DE BOLANOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,463,830','JUAN','DE JESUS','SERNA','OSSA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,038','APOLONIA','','SANCHEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,493,429','MARIO','ARNULFO','GARCIA','ORTIZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,712,904','PAULINA','','MENDEZ','DE RAMOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,459','MARIA','DORALINA','TORRES','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,498,455','ROSA','MARIA','ORTIZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,145,144','ZOILA','ROSA','REAL','VIRGUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,051,665','RAFAEL','ANTONIO','GOMEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,189','JAIRO','ENRIQUE','SANTIAGO','ALFONSO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,128,691','RAMON','','PINEDA','LATON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,337,279','ANTONIO','','RIOBO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,290,790','HECTOR','RAUL','DUARTE','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,070,705,946','JOSE','FACUNDO','BENAVIDEZ','CARDENAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('126,223','ARISTIPO','','MARTINEZ','RAMIREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('24,925,432','MARIA','NELLY','TORRES','ALVAREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,232,550','JOSE','ARNALDO','GARCIA','GIRALDO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,240','ANIBAL','','GARCIA','LOPEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,270,086','MARIA','NELLY','MORENO','AVILA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,199,941','MARIA','DE JESUS','HERNANDEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,962,519','ERASMO','','CUTIVA','CULMA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,712,230','CARLINA','','GOMEZ','DE ALVARADO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,261','ERESMILDO','','CUELLAR','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('31,006,103','LUCILA','','POVEDA','FRANCO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,004,314','SERAFIN','','NOVOA','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,247,887','JESUS','ANTONIO','MELO','MORALES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,294,264','ABRAHAM','','GARCIA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,785,809','SUSANA','','RAMIREZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,070,202','MARIELA','DE JESUS','VASQUEZ','OSPINA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,893,028','DESIDERIA','','ZAMUDIO','CALVO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,282,728','JUAN','DEDIOS','PRIETO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,871','SALVADOR','','GALINDO','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('497,042','JUAN','ESTEBAN','REY','VALDERRAMA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,868','CARLOTA','','LONDONO','PEREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,200,010','ANA','','OSORIO','CAPERA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,255,738','JORGE','ABEL','GARCIA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,002,656','LUZ','MERY','AGUDELO','SANCHEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,259,131','RAFAEL','','VEGA','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,972,368','SOR','CELINA','CALLE','JARAMILLO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,753','JOSE','OLIVO','SUAREZ','MEDELLIN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,597','ADELAIDA','','GAVIRIA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,319','OBDULIO','','RIVERA','GALEON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,191,978','DIOGENES','','SARMIENTO','CRUZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,319','MARIA','AMPARO','RESTREPO','DE GOMEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,457,578','JOSE','DOMINGO','SERNA','OSSA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,349,009','GILBERTO','','OSORIO','PERDOMO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,216,252','EMILCE','','QUEVEDO','DE ROJAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,193,771','ELOYDINA','','TELLEZ','DE ARIZA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,202,758','FANNY','','VARGAS','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,041,762','LUIS','EFRAIN','PEREZ','MENDOZA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,149','JAIME','','CHUQUEN','CALDERON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,500,738','ANA','ROSA','DIAZ','DE RODRIGUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,115,318','ROSA','MARIA','VILLABON','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,465','MARIA','OMEDI','OSORIO','QUINTERO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,806,412','LILIA','','ECHEVERRY','JIMENEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,982,922','MARIA','EVELIA','CUADROS','DE CUERVO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,235,282','ABIGAIL','','BARRERA','MARTINEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,816,681','MARCO','FIDEL','AGUIAR','OVIEDO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,275,223','LUIS','OSCAR','RAMIREZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,323,093','MILCIADES','','GUERRERO','MORENO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,282,369','ELIO','FABIO','CAPERA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,825,030','ESNEDA','','GOMEZ','DE VERGARA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,823','REINALDO','','SANCHEZ','PERDOMO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('316,081','ENRIQUE','','GOMEZ','GOMEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,239,757','RICARDO','','GARCIA','PALACIO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,123,058,435','ROSA','','SANCHEZ','ROJAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,265,927','CASIMIRO','','FIGUEROA','MONTEALEGRE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,665,401','SIGIFREDO','','RESTREPO','ATEHORTURA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,082,905','DOMINGO','','PICO','CANELO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,173','MATILDE','','CESPEDES','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,323,181','JOSE','EUDORO','CESPEDES','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,631','CLAUDIO','','SANCHEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,120,026,176','FLORINDA','','CARDENAS','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,139','IRMA','ISABEL','PINEDA','DE ROA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,795','ALFONSO','','GOMEZ','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,842,671','GRACIELA','','RAMIREZ','DE BARRIOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('311,413','ISIDRO','','ORJUELA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,252,679','JOSE','HORACIO','MARTINEZ','OLAYA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,392,235','SAMUEL','','ARDILA','QUIROGA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('11,210,015','ULPIANO','','CANTE','MARTINEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('31,036,562','ANA','VICTORIA','ALEY','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,224,017','AURELIO','','LEAL','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,369,505','BERNARDINO','','CARDOZO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,007,750','ANA','GRACIELA','RAMIREZ','VARGAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,972,012','MARIA','LIBIA','RESTREPO','RAVE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,209,481','BLANCA','ALCIRA','HERRERA','DE PINZON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,240,391','JOSE','BAUTISTA','MARALES','MORALES');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,618,653','PEDRO','ELIAS','CABANZO','SERRANO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,993','MARY','','CARDONA','DE OCHOA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,350,993','JESUS','ALFONSO','ECHEVERRY','CANO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('17,350,507','JORGE','ENRIQUE','RODRIGUEZ','CAICEDO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,663,536','SERGIO','','ARIZA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('26,429,343','ROSA','MARIA','VALDERRAMA','GONZALEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,752','MARIA','ISAURA','GARCIA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('454,738','PRIMITIVO','','VILLABON','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,156,316','CELINA','','RAMIREZ','DE SUAREZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,726','EMMA','TEOFILDE','SAAVEDRA','DE ARANDA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('482,185','ABEL','ANTONIO','CARDOZO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('482,391','JUAN','NEPOMUCENO','GONZALEZ','VERDUGO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('26,499,584','FIDELINA','','TUMBO','VARGAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,338,382','CAMPO','ELIAS','HERNANDEZ','RAMOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,000','HERNAN','','SALAZAR','SILVA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,488,779','HERNANDO','DE JESUS','GIRALDO','MOLINA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('24,700,417','ANA','RITA','HUERTAS','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,405','MARIA','ERNESTINA','OCHOA','DE BECERRA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,810,268','MARIA','REGINA','PARRA','GIL');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,972,138','ORTENCIA','','GARCIA','VARGAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('460,156','JOSE','RODRIGO','FORERO','BERNAL');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,537,060','GEDEON','','TABORDA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,133,080','PASTOR','EMILIO','ARANGO','BEDOYA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,202,022','FLOR','NELLY','MONTILLA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,200,345','MARLENE','','GONZALEZ','MOLINA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('40,200,037','LUZ','MARY','GUERRERO','LOZADA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,002,640','RAYMUNDA','','LONDONO','VANEGAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,198,581','CARMELINA','','LAVERDE','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,504,574','JOSE','TULIO','ORJUELA','DIAZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('310,233','LUIS','EDUARDO','ORJUELA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,792,192','ALVARO','','CUERVO','BALLESTEROS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,023,782','MARIA','ISIDORA','MARIN','DE RIVERA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,093,391','ARQUIMEDES','','GUERRERO','BELTRAN');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('28,304,302','TRANSITO','','CAVANZO','DE GONZALEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,451','JORGE','ARGEMIRO','RUBIO','GONZALEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,810,705','LILIA','','GOMEZ','DE VILLABON');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,115,652','BLANCA','SOFIA','CORTES','CASAS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,489,841','LUIS','ALBERTO','REAL','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,462,242','JULIO','CESAR','ARBOLEDA','ECHEVERRY');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,206,333','MARIA','DILIA','CEBALLOS','DE RODRIGUEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,690,706','BLANCA','ESMILDA','RUBIO','DE HERRERA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('226,549','JOSE','NICOLAS','ESPITIA','MUÑOZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,488,308','ISRAEL','','CAÑON','OVALLE');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('5,987,406','HUMBERTO','','LONDOÑO','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,322,831','CARLOS','JULIO','TRIVIÑO','JARA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,004,822','MARIA','DARLEY','MOLINA','ZUÑIGA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,798,560','HERMELINDA','','MARIN','CASTAÑEDA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,268,071','FAUSTINO','','BRIÑEZ','CHICO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,200,191','ADELA','LEONOR','GOMEZ','PEÑA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('79,110,116','VICENTE','','CAÑON','QUIROGA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('9,048,954','JACOBO','','ALVAREZ','BOLAÑOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,197,776','TERESA','DE JESUS','CAÑAVERAL','DE QUINTERO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,282,751','CARLOS','JULIO','SAAVEDRA','PEÑA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('16,202,741','NICACIO','DE JESUS','ZAPATA','CASTAÑO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,280,945','ALFONSO','','LONDOÑO','PARRA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,162,405','MARIA','ELENA','UÑATE','DE PRECIADO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,803,193','MARIA','AGRIPINA','CASTAÑEDA','DE RUIZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('20,711,497','SOLEDAD','','CASTA?æEDA','ORDO?æEZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,971,166','MARIA','DEL ROSARIO','PEÐA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,342,053','JOSE','GABRIEL','DIAZ','LONDOÑO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,488,334','LUIS','EVELIO','LONDOÐO','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('3,281,242','JOSE','YESID','PEÑALOSA','');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('23,489,521','ROSA','MARINA','RUIZ','DE CASTAÑEDA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('29,386,019','MARIA','SOLEDAD','CASTAÑO','DE ZAPATA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('30,972,335','FLOR','ELISA','MORALES','BAÑOL');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,231,864','LUIS','NERRIQUE','REYES','FANDIÐO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,205,678','NINA','MARIA','LONDOÑO','DE AVELLA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,267,447','MATEO','','BRIÑEZ','CHICO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('63,674','ARQUIMEDES','.','ALVAREZ','BOLAÑOS');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,488,060','EUFEMIANO','','SAAVEDRA','PEÑA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('4,726,032','LUCAS','','PEÑA','YAFI');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('7,490,974','JORGE','','MOLINA','ZUÐIGA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('6,664,654','ADAN','','CICUA','MUÑOZ');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('2,398,376','VICTOR','MANUEL','IBAÑEZ','.');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('19,130,975','JOSE','ISAURO','ROSO','CASTAÑEDA');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('21,213,906','BLANCA','CENELIA','CRUZ','DE LONDOÑO');
insert into Adultos(cedula,primernombre,segundonombre,primerapellido,segundoapellido) VALUES ('1,509,578','MANUEL','ANTONIO','ZUÑIGA','');
